### PR TITLE
Additional changes and features (barely working)

### PR DESCRIPTION
**Pull request by danieldia-dev**

### CODE REVIEW

**Review by Sammy99jsp — APPROVED** [review]
Was under my supervision whilst doing the big things.
Does compile and display properly, although very messy(!)

**Comment by MrSerge01** [comment]
> Was under my supervision whilst doing the big things.
> Does compile and display properly, although very messy(!)

lol
I bet when Sammy says it, he just carried Kibal here LMAO
(no offense)

**Comment by ghost** [comment]
> 

(13.48383839% offense)

**Comment by ghost** [comment]
Why the pr was closed? "First of all, do you remember that i said on the discord server to not follow the widget gallery method? If you don't rember or you don't saw the message, it's not my fault, second: i saw some merge conflicts that haven't been fixed, and third: divide code in more files and code guidelines."

**Comment by ghost** [comment]
Also what's that "barely working" phrase? If the pr wasn't even finished why you commited it?

**Pull request closed without merging**
