### PR TITLE
Create and update .gitignore

### PR DESCRIPTION
**Pull request by lucasod3v**
I hate that ```cargo run``` always creates a mess in /target/ so I made the .gitignore fike to remove two files that clutters the repo.

excluded files/folder:
```
/target/

Cargo.lock
```

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by StoneMcYT — APPROVED** [review]
LGTM

**Review by Froxcey — COMMENTED** [review]
Ummm... Maybe you can end the file with endline?

**Comment by ghost** [comment]
> Ummm... Maybe you can end the file with endline?

Done

**Review by Froxcey — APPROVED** [review]
Great, good

vibe

**Pull request merged**
